# Generated by Django 5.2.17 on 2026-09-30 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("cor", models.CharField(default="#4f8cff", max_length=7)),
                ("meta_horas_semanais", models.FloatField(default=0)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Topico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nao_iniciado", "Não iniciado"),
                            ("estudando", "Estudando"),
                            ("revisado", "Revisado"),
                            ("dominado", "Dominado"),
                        ],
                        default="nao_iniciado",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos",
                        to="estudos.materia",
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filhos",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SessaoEstudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(default=django.utils.timezone.now)),
                ("duracao_min", models.PositiveIntegerField(default=0)),
                ("nota", models.TextField(blank=True)),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="Revisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_prevista", models.DateField()),
                ("feita", models.BooleanField(default=False)),
                ("dificil", models.BooleanField(default=False)),
                ("feita_em", models.DateTimeField(blank=True, null=True)),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["data_prevista"],
            },
        ),
        migrations.CreateModel(
            name="BlocoPlanejado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana", models.DateField(help_text="segunda-feira da semana")),
                ("dia_semana", models.PositiveSmallIntegerField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocos",
                        to="estudos.materia",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocos",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
    ]
