# Generated by Django 5.2.17 on 2026-10-04 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocoplanejado",
            name="tipo",
            field=models.CharField(
                choices=[("aula", "Aula"), ("estudo", "Estudo"), ("outro", "Outro")],
                default="estudo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="blocoplanejado",
            name="titulo",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="blocoplanejado",
            name="materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocos",
                to="estudos.materia",
            ),
        ),
        migrations.AlterField(
            model_name="blocoplanejado",
            name="semana",
            field=models.DateField(
                blank=True,
                help_text="segunda-feira da semana; vazio = toda semana",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OcorrenciaPulada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana", models.DateField()),
                (
                    "bloco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puladas",
                        to="estudos.blocoplanejado",
                    ),
                ),
            ],
            options={
                "unique_together": {("bloco", "semana")},
            },
        ),
    ]
