# Generated by Django 5.2.17 on 2026-10-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0002_blocoplanejado_tipo_blocoplanejado_titulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocoplanejado",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
