# Generated by Django 5.2.17 on 2026-10-04 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0003_blocoplanejado_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prova", "Prova"),
                            ("trabalho", "Trabalho"),
                            ("outro", "Outro"),
                        ],
                        default="prova",
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateField()),
                ("hora", models.TimeField(blank=True, null=True)),
                (
                    "peso",
                    models.FloatField(
                        default=0, help_text="peso na media; 0 = nao informado"
                    ),
                ),
                ("nota", models.FloatField(blank=True, null=True)),
                ("concluida", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="estudos.materia",
                    ),
                ),
                (
                    "topicos",
                    models.ManyToManyField(
                        blank=True, related_name="avaliacoes", to="estudos.topico"
                    ),
                ),
            ],
            options={
                "ordering": ["data", "hora"],
            },
        ),
    ]
