# Generated by Django 5.2.17 on 2026-10-04 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0004_avaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisao",
            name="qualidade",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="0 a 5, a nota que o SM-2 recebeu", null=True
            ),
        ),
        migrations.AddField(
            model_name="topico",
            name="acertos_seguidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topico",
            name="facilidade",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="topico",
            name="intervalo_dias",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Cartao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frente", models.TextField()),
                ("verso", models.TextField()),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartoes",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
    ]
