# Generated by Django 5.2.17 on 2026-10-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0006_uma_revisao_pendente_por_topico"),
    ]

    operations = [
        migrations.AddField(
            model_name="topico",
            name="notas",
            field=models.TextField(blank=True, help_text="resumo livre do topico"),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("arquivo", models.FileField(blank=True, upload_to="materiais/")),
                (
                    "nota",
                    models.CharField(
                        blank=True, help_text="página, capítulo…", max_length=200
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
