# Generated by Django 5.2.17 on 2026-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0007_topico_notas_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoestudo",
            name="interrupcoes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
