# Generated by Django 5.2.17 on 2026-10-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0008_sessaoestudo_interrupcoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primeiro_intervalo_dias",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("segundo_intervalo_dias", models.PositiveSmallIntegerField(default=6)),
                ("facilidade_minima", models.FloatField(default=1.3)),
                (
                    "intervalo_maximo_dias",
                    models.PositiveSmallIntegerField(default=365),
                ),
                (
                    "maximo_revisoes_por_dia",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="0 = sem teto"
                    ),
                ),
                ("meta_horas_semanais", models.FloatField(default=10)),
                ("dias_materia_parada", models.PositiveSmallIntegerField(default=7)),
                (
                    "dias_proximas_avaliacoes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("pomodoro_foco_min", models.PositiveSmallIntegerField(default=25)),
                ("pomodoro_pausa_min", models.PositiveSmallIntegerField(default=5)),
                (
                    "pomodoro_pausa_longa_min",
                    models.PositiveSmallIntegerField(default=15),
                ),
                ("pomodoro_ciclos", models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                "verbose_name": "configuração",
            },
        ),
    ]
