# Generated by Django 5.2.17 on 2026-10-04 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0009_configuracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaRevisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualidade",
                    models.PositiveSmallIntegerField(help_text="0 a 5, a nota do SM-2"),
                ),
                (
                    "respondida_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_prevista",
                    models.DateField(
                        help_text="o dia para que a revisao estava marcada"
                    ),
                ),
                (
                    "atraso_dias",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="dias entre o previsto e o respondido"
                    ),
                ),
                ("status_antes", models.CharField(max_length=20)),
                ("facilidade_antes", models.FloatField()),
                ("intervalo_antes", models.PositiveIntegerField()),
                ("acertos_antes", models.PositiveIntegerField()),
                ("facilidade_depois", models.FloatField()),
                ("intervalo_depois", models.PositiveIntegerField()),
                (
                    "revisao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="estudos.revisao",
                    ),
                ),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="estudos.topico",
                    ),
                ),
            ],
            options={
                "verbose_name": "resposta de revisão",
                "verbose_name_plural": "respostas de revisão",
                "ordering": ["-respondida_em", "-id"],
            },
        ),
    ]
