# Generated by Django 5.2.17 on 2026-10-05 01:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0011_configuracao_folgas_por_semana"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40, unique=True)),
                ("foto", models.FileField(blank=True, upload_to="perfis/")),
                ("cor", models.CharField(default="#c2410c", max_length=7)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("ultimo_acesso", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfis",
                "ordering": ["-ultimo_acesso", "nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="avaliacao",
            options={"base_manager_name": "todos", "ordering": ["data", "hora"]},
        ),
        migrations.AlterModelOptions(
            name="blocoplanejado",
            options={
                "base_manager_name": "todos",
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
        migrations.AlterModelOptions(
            name="cartao",
            options={"base_manager_name": "todos", "ordering": ["ordem", "id"]},
        ),
        migrations.AlterModelOptions(
            name="configuracao",
            options={"base_manager_name": "todos", "verbose_name": "configuração"},
        ),
        migrations.AlterModelOptions(
            name="materia",
            options={"base_manager_name": "todos", "ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"base_manager_name": "todos", "ordering": ["-criado_em"]},
        ),
        migrations.AlterModelOptions(
            name="ocorrenciapulada",
            options={"base_manager_name": "todos"},
        ),
        migrations.AlterModelOptions(
            name="respostarevisao",
            options={
                "base_manager_name": "todos",
                "ordering": ["-respondida_em", "-id"],
                "verbose_name": "resposta de revisão",
                "verbose_name_plural": "respostas de revisão",
            },
        ),
        migrations.AlterModelOptions(
            name="revisao",
            options={"base_manager_name": "todos", "ordering": ["data_prevista"]},
        ),
        migrations.AlterModelOptions(
            name="sessaoestudo",
            options={"base_manager_name": "todos", "ordering": ["-inicio"]},
        ),
        migrations.AlterModelOptions(
            name="topico",
            options={"base_manager_name": "todos", "ordering": ["nome"]},
        ),
        migrations.AlterModelManagers(
            name="avaliacao",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blocoplanejado",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="cartao",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="configuracao",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="materia",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="material",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="ocorrenciapulada",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="respostarevisao",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="revisao",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sessaoestudo",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="topico",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="materia",
            name="nome",
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="blocoplanejado",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="cartao",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="ocorrenciapulada",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="respostarevisao",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="revisao",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="sessaoestudo",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddField(
            model_name="topico",
            name="perfil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="estudos.perfil",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracao",
            constraint=models.UniqueConstraint(
                fields=("perfil",), name="uma_configuracao_por_perfil"
            ),
        ),
        migrations.AddConstraint(
            model_name="materia",
            constraint=models.UniqueConstraint(
                fields=("perfil", "nome"), name="materia_unica_por_perfil"
            ),
        ),
    ]
