# Generated by Django 5.2.17 on 2026-10-05 02:23

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0014_perfil_obrigatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracao",
            name="lembrete_ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configuracao",
            name="lembrete_hora",
            field=models.TimeField(
                blank=True,
                help_text="vazio = o horário em que você costuma estudar",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Marco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chave", models.CharField(max_length=60)),
                ("titulo", models.CharField(max_length=80)),
                ("detalhe", models.CharField(blank=True, max_length=160)),
                (
                    "conquistado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="estudos.perfil",
                    ),
                ),
            ],
            options={
                "ordering": ["-conquistado_em", "-id"],
                "abstract": False,
                "base_manager_name": "todos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("perfil", "chave"), name="um_marco_por_chave_e_perfil"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("todos", django.db.models.manager.Manager()),
            ],
        ),
    ]
