from django.urls import path

from . import views

urlpatterns = [
    # paginas
    path("", views.pagina_dashboard, name="dashboard"),
    # A URL que abre o app ja estudando; e o start_url do atalho do celular.
    path("agora/", views.ir_para_agora, name="agora"),
    path("materias/", views.pagina_materias, name="materias"),
    path("sessao/", views.pagina_sessao, name="sessao"),
    path("planner/", views.pagina_planner, name="planner"),
    path("quadro/", views.pagina_quadro, name="quadro"),
    path("revisar/", views.pagina_revisar, name="revisar"),
    path("avaliacoes/", views.pagina_avaliacoes, name="avaliacoes"),
    path("historico/", views.pagina_historico, name="historico"),
    path("configuracoes/", views.pagina_configuracoes, name="configuracoes"),
    path("dados/", views.pagina_dados, name="dados"),
    # Precisa estar na raiz para o service worker controlar o app todo.
    path("sw.js", views.service_worker, name="service-worker"),
    # api
    path("api/dashboard/", views.api_dashboard),
    path("api/materias/", views.api_materias),
    path("api/materias/criar/", views.api_materia_criar),
    path("api/materias/<int:pk>/editar/", views.api_materia_editar),
    path("api/materias/<int:pk>/excluir/", views.api_materia_excluir),
    path("api/arvore/", views.api_arvore),
    path("api/topicos/", views.api_topicos),
    path("api/topicos/criar/", views.api_topico_criar),
    path("api/topicos/<int:pk>/editar/", views.api_topico_editar),
    path("api/topicos/<int:pk>/status/", views.api_topico_status),
    path("api/topicos/<int:pk>/excluir/", views.api_topico_excluir),
    path("api/sessoes/", views.api_sessoes),
    path("api/sessoes/criar/", views.api_sessao_criar),
    path("api/sessoes/<int:pk>/excluir/", views.api_sessao_excluir),
    path("api/planner/", views.api_planner),
    path("api/blocos/criar/", views.api_bloco_criar),
    path("api/blocos/<int:pk>/editar/", views.api_bloco_editar),
    path("api/blocos/<int:pk>/excluir/", views.api_bloco_excluir),
    path("api/blocos/<int:pk>/pular/", views.api_bloco_pular),
    path("api/planner/importar-ical/", views.api_importar_ical),
    path("api/revisoes/hoje/", views.api_revisoes_hoje),
    path("api/carga/", views.api_carga),
    path("api/revisoes/<int:pk>/cartoes/", views.api_revisao_cartoes),
    path("api/revisoes/<int:pk>/responder/", views.api_revisao_responder),
    path("api/revisoes/desfazer/", views.api_revisao_desfazer),
    path("api/cartoes/", views.api_cartoes),
    path("api/cartoes/criar/", views.api_cartao_criar),
    path("api/cartoes/surpresa/", views.api_cartao_surpresa),
    path("api/topicos/<int:pk>/cartoes-da-nota/", views.api_cartoes_da_nota),
    path("api/cartoes/<int:pk>/editar/", views.api_cartao_editar),
    path("api/cartoes/<int:pk>/excluir/", views.api_cartao_excluir),
    path("api/historico/", views.api_historico),
    path("api/busca/", views.api_busca),
    path("api/configuracoes/", views.api_configuracoes),
    path("api/configuracoes/salvar/", views.api_configuracoes_salvar),
    path("api/materiais/", views.api_materiais),
    path("api/materiais/criar/", views.api_material_criar),
    path("api/materiais/<int:pk>/excluir/", views.api_material_excluir),
    path("api/avaliacoes/", views.api_avaliacoes),
    path("api/avaliacoes/criar/", views.api_avaliacao_criar),
    path("api/avaliacoes/<int:pk>/editar/", views.api_avaliacao_editar),
    path("api/avaliacoes/<int:pk>/plano/", views.api_avaliacao_plano),
    path("api/avaliacoes/<int:pk>/excluir/", views.api_avaliacao_excluir),
    path("api/backup/exportar/", views.api_backup_exportar),
    path("api/backup/importar/", views.api_backup_importar),
]
